const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {URL}=require('url');
const store=require('./storage');

const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), DB_PATH=path.join(ROOT,'data','db.json');
const PORT=Number(process.env.PORT||3000);
const ADMIN_USER=process.env.ADMIN_USER||'admin';
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'ChangeMe-CloudKey-2026!';
const SESSION_SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
const sessions=new Map(),loginAttempts=new Map(),rateBuckets=new Map();

function readDB(){return store.read()}
function writeDB(db){return store.write(db)}
function json(res,status,data,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(JSON.stringify(data))}
function body(req,limit=2500000){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>limit){req.destroy();reject(new Error('body_too_large'))}});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}});req.on('error',reject)})}
function parseCookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}))}
function getSession(req){const sid=parseCookies(req).ck_session,s=sid&&sessions.get(sid);if(!s)return null;if(Date.now()-s.created>28800000){sessions.delete(sid);return null}return s}
function requireAdmin(req,res){if(!getSession(req)){json(res,401,{error:'unauthorized'});return false}return true}
function safeId(){return crypto.randomUUID()}
function orderNo(){const d=new Date(),day=`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;return `CK-${day}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`}
function validPhone(v){return /^(\+?966|0)?5\d{8}$/.test(String(v||'').replace(/\s|-/g,''))}
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function hasImage(p){return typeof p.image==='string'&&p.image.length>20}
function bearer(req){const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7).trim():''}
function audit(db,action,meta={}){db.audit||=[];db.audit.unshift({id:safeId(),at:new Date().toISOString(),action,meta});db.audit=db.audit.slice(0,1000)}
function rate(req,key,limit,windowMs){const id=key+':'+clientIp(req),now=Date.now(),r=rateBuckets.get(id)||{start:now,count:0};if(now-r.start>windowMs){r.start=now;r.count=0}r.count++;rateBuckets.set(id,r);return r.count<=limit}
function sameOrigin(req){const o=String(req.headers.origin||'');if(!o)return true;try{return new URL(o).host===String(req.headers.host||'')}catch{return false}}

async function firebaseUser(req){const token=bearer(req),key=process.env.FIREBASE_API_KEY||'';if(!token||!key)return null;try{const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idToken:token})});if(!r.ok)return null;const out=await r.json(),u=out.users?.[0];if(!u?.localId)return null;return {uid:u.localId,email:u.email||'',phone:u.phoneNumber||'',name:u.displayName||'',photo:u.photoUrl||'',providers:(u.providerUserInfo||[]).map(x=>x.providerId)}}catch{return null}}
async function requireCustomer(req,res){const u=await firebaseUser(req);if(!u){json(res,401,{error:'login_required'});return null}return u}
function publicOrder(o){return {number:o.number,status:o.status,total:o.total,subtotal:o.subtotal,discount:o.discount,createdAt:o.createdAt,items:o.items,delivery:['paid','processing','completed'].includes(o.status)?o.delivery:[],payment:{provider:o.payment?.provider||'',status:o.payment?.status||''}}}
function markPaid(db,o,payment={}){if(['paid','processing','completed'].includes(o.status))return o;o.status='paid';o.payment={...(o.payment||{}),provider:payment.provider||o.payment?.provider||'moyasar',status:'paid',id:payment.id||o.payment?.id||'',paidAt:new Date().toISOString()};for(const item of o.items||[]){const p=db.products.find(p=>p.id===item.id);if(p)p.stock=Math.max(0,Number(p.stock||0)-Number(item.qty||0))}o.delivery=[];for(const item of o.items||[]){const available=db.codes.filter(c=>c.productId===item.id&&!c.usedAt).slice(0,item.qty);available.forEach(c=>{c.usedAt=new Date().toISOString();c.orderId=o.id;o.delivery.push({productId:item.id,code:c.code})})}audit(db,'order_paid',{order:o.number,paymentId:payment.id||''});return o}
async function moyasarPayment(id){const sk=String(process.env.MOYASAR_SECRET_KEY||'');if(!sk||!id)return null;try{const r=await fetch(`https://api.moyasar.com/v1/payments/${encodeURIComponent(id)}`,{headers:{authorization:'Basic '+Buffer.from(sk+':').toString('base64')}});if(!r.ok)return null;return await r.json()}catch{return null}}
function paymentMatches(p,o){const meta=p?.metadata||{};return p?.status==='paid'&&p?.currency==='SAR'&&Number(p.amount)===Math.round(Number(o.total)*100)&&String(meta.order_number||meta.orderNumber||'')===String(o.number)}

async function api(req,res,url){
  if(!rate(req,'api',240,60000))return json(res,429,{error:'rate_limited'});
  if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,service:'cloud-key-v5',storage:store.info()});
  if(req.method==='GET'&&url.pathname==='/api/firebase-config')return json(res,200,{apiKey:process.env.FIREBASE_API_KEY||'',authDomain:process.env.FIREBASE_AUTH_DOMAIN||'',projectId:process.env.FIREBASE_PROJECT_ID||'',storageBucket:process.env.FIREBASE_STORAGE_BUCKET||'',messagingSenderId:process.env.FIREBASE_MESSAGING_SENDER_ID||'',appId:process.env.FIREBASE_APP_ID||''});
  if(req.method==='GET'&&url.pathname==='/api/payment-config')return json(res,200,{provider:'moyasar',enabled:!!process.env.MOYASAR_PUBLISHABLE_KEY,publishableKey:process.env.MOYASAR_PUBLISHABLE_KEY||'',methods:['creditcard',...(process.env.MOYASAR_STC_PAY==='true'?['stcpay']:[]),...(process.env.MOYASAR_APPLE_PAY==='true'?['applepay']:[])],applePay:process.env.MOYASAR_APPLE_PAY==='true'});
  if(req.method==='GET'&&url.pathname==='/api/products'){const db=readDB();return json(res,200,db.products.filter(p=>p.active&&p.stock!==0&&hasImage(p)).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)))}
  const publicProduct=url.pathname.match(/^\/api\/products\/([^/]+)$/);if(publicProduct&&req.method==='GET'){const db=readDB(),p=db.products.find(p=>p.id===publicProduct[1]&&p.active&&hasImage(p));return p?json(res,200,p):json(res,404,{error:'not_found'})}

  if(req.method==='GET'&&url.pathname==='/api/me'){const u=await requireCustomer(req,res);if(!u)return;const db=readDB(),orders=db.orders.filter(o=>o.customer?.uid===u.uid);return json(res,200,{...u,orders:orders.length,totalSpent:orders.filter(o=>['paid','processing','completed'].includes(o.status)).reduce((s,o)=>s+Number(o.total||0),0)})}
  if(req.method==='GET'&&url.pathname==='/api/my/orders'){const u=await requireCustomer(req,res);if(!u)return;const db=readDB();return json(res,200,db.orders.filter(o=>o.customer?.uid===u.uid).map(publicOrder))}
  const myOrder=url.pathname.match(/^\/api\/my\/orders\/([^/]+)$/);if(myOrder&&req.method==='GET'){const u=await requireCustomer(req,res);if(!u)return;const db=readDB(),number=decodeURIComponent(myOrder[1]).toUpperCase(),o=db.orders.find(o=>o.customer?.uid===u.uid&&String(o.number).toUpperCase()===number);return o?json(res,200,publicOrder(o)):json(res,404,{error:'not_found'})}
  if(req.method==='GET'&&url.pathname==='/api/order-status'){const u=await requireCustomer(req,res);if(!u)return;const number=(url.searchParams.get('number')||'').trim().toUpperCase(),db=readDB(),o=db.orders.find(o=>o.customer?.uid===u.uid&&String(o.number).toUpperCase()===number);return o?json(res,200,publicOrder(o)):json(res,404,{error:'not_found'})}

  if(req.method==='POST'&&url.pathname==='/api/checkout'){
    if(!rate(req,'checkout',20,60000))return json(res,429,{error:'rate_limited'});const u=await requireCustomer(req,res);if(!u)return;
    try{const b=await body(req);if(!Array.isArray(b.items)||!b.items.length)return json(res,400,{error:'invalid_order'});const contactPhone=u.phone||String(b.phone||'');if(!validPhone(contactPhone))return json(res,400,{error:'phone_required'});const db=readDB();let subtotal=0;const items=[];for(const x of b.items){const p=db.products.find(p=>p.id===x.id&&p.active&&hasImage(p));const qty=Math.max(1,Math.min(10,Number(x.qty)||1));if(!p||p.stock<qty)return json(res,409,{error:'out_of_stock',productId:x.id});subtotal+=Number(p.price)*qty;items.push({id:p.id,name:p.name,price:Number(p.price),qty,image:p.image||''})}let discount=0;const coupon=String(b.coupon||'').trim().toUpperCase();if(coupon){const c=db.coupons.find(c=>c.active&&c.code===coupon);if(c)discount=Math.round(subtotal*Number(c.percent||0))/100}const total=Math.max(0,subtotal-discount),order={id:safeId(),number:orderNo(),createdAt:new Date().toISOString(),customer:{uid:u.uid,name:u.name||String(b.name||'عميل Cloud Key').slice(0,100),email:u.email||String(b.email||'').slice(0,150),phone:contactPhone,provider:u.providers?.[0]||'firebase'},items,subtotal,discount,total,coupon,status:'pending_payment',payment:{provider:process.env.MOYASAR_PUBLISHABLE_KEY?'moyasar':'manual',status:'not_started'},delivery:[]};db.orders.unshift(order);audit(db,'order_created',{order:order.number,uid:u.uid,total});writeDB(db);return json(res,201,{orderNumber:order.number,total:order.total,status:order.status,paymentReady:!!process.env.MOYASAR_PUBLISHABLE_KEY,paymentProvider:process.env.MOYASAR_PUBLISHABLE_KEY?'moyasar':'manual'})}catch{return json(res,400,{error:'bad_request'})}
  }
  if(req.method==='POST'&&url.pathname==='/api/payment/verify'){
    const u=await requireCustomer(req,res);if(!u)return;try{const b=await body(req,100000),db=readDB(),o=db.orders.find(o=>o.number===String(b.orderNumber||'').toUpperCase()&&o.customer?.uid===u.uid);if(!o)return json(res,404,{error:'order_not_found'});const p=await moyasarPayment(String(b.paymentId||''));if(!p||!paymentMatches(p,o))return json(res,409,{error:'payment_not_verified'});markPaid(db,o,{provider:'moyasar',id:p.id});writeDB(db);return json(res,200,{ok:true,order:publicOrder(o)})}catch{return json(res,400,{error:'bad_request'})}
  }
  if(req.method==='POST'&&url.pathname==='/api/payment/webhook'){
    try{const b=await body(req,500000);if(!process.env.MOYASAR_WEBHOOK_SECRET||String(b.secret_token||'')!==String(process.env.MOYASAR_WEBHOOK_SECRET))return json(res,401,{error:'invalid_webhook'});const p=b.data,orderNumber=String(p?.metadata?.order_number||'');if(b.type!=='payment_paid'||!orderNumber)return json(res,200,{ok:true,ignored:true});const db=readDB(),o=db.orders.find(o=>o.number===orderNumber);if(!o||!paymentMatches(p,o))return json(res,409,{error:'payment_mismatch'});markPaid(db,o,{provider:'moyasar',id:p.id});writeDB(db);return json(res,200,{ok:true})}catch{return json(res,400,{error:'bad_request'})}
  }

  if(req.method==='POST'&&url.pathname==='/api/admin/login'){
    if(!rate(req,'admin-login',15,15*60000))return json(res,429,{error:'too_many_attempts'});try{const ip=clientIp(req),now=Date.now(),rec=loginAttempts.get(ip)||{count:0,until:0};if(rec.until>now)return json(res,429,{error:'too_many_attempts'});const b=await body(req,50000);const userOk=crypto.timingSafeEqual(Buffer.from(String(b.username||'').padEnd(ADMIN_USER.length,'\0').slice(0,ADMIN_USER.length)),Buffer.from(ADMIN_USER));const bp=Buffer.from(String(b.password||'')),ap=Buffer.from(ADMIN_PASSWORD);const passOk=bp.length===ap.length&&crypto.timingSafeEqual(bp,ap);if(!userOk||!passOk){rec.count++;if(rec.count>=5){rec.until=now+15*60*1000;rec.count=0}loginAttempts.set(ip,rec);return json(res,401,{error:'invalid_credentials'})}loginAttempts.delete(ip);const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{user:ADMIN_USER,created:Date.now(),proof:crypto.createHmac('sha256',SESSION_SECRET).update(sid).digest('hex')});res.setHeader('Set-Cookie',`ck_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`);const db=readDB();audit(db,'admin_login',{ip});writeDB(db);return json(res,200,{ok:true})}catch{return json(res,400,{error:'bad_request'})}
  }
  if(req.method==='POST'&&url.pathname==='/api/admin/logout'){const sid=parseCookies(req).ck_session;if(sid)sessions.delete(sid);res.setHeader('Set-Cookie','ck_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
  if(url.pathname.startsWith('/api/admin/')&&!requireAdmin(req,res))return;
  if(url.pathname.startsWith('/api/admin/')&&['POST','PUT','PATCH','DELETE'].includes(req.method)&&!sameOrigin(req))return json(res,403,{error:'origin_rejected'});
  if(req.method==='GET'&&url.pathname==='/api/admin/overview'){const db=readDB();return json(res,200,{products:db.products,orders:db.orders,coupons:db.coupons,codes:db.codes,storage:store.info()})}
  if(req.method==='GET'&&url.pathname==='/api/admin/customers'){const db=readDB(),m=new Map();for(const o of db.orders){const id=o.customer?.uid||o.customer?.email||o.customer?.phone;if(!id)continue;const x=m.get(id)||{uid:o.customer?.uid||'',name:o.customer?.name||'عميل',email:o.customer?.email||'',phone:o.customer?.phone||'',orders:0,paidOrders:0,totalSpent:0,lastOrder:null};x.orders++;if(['paid','processing','completed'].includes(o.status)){x.paidOrders++;x.totalSpent+=Number(o.total||0)}if(!x.lastOrder||new Date(o.createdAt)>new Date(x.lastOrder))x.lastOrder=o.createdAt;m.set(id,x)}return json(res,200,[...m.values()].sort((a,b)=>b.totalSpent-a.totalSpent))}
  if(req.method==='GET'&&url.pathname==='/api/admin/analytics'){const db=readDB(),paid=db.orders.filter(o=>['paid','processing','completed'].includes(o.status)),now=Date.now(),day=86400000;const revenue=paid.reduce((s,o)=>s+Number(o.total||0),0),today=paid.filter(o=>now-new Date(o.createdAt).getTime()<day).reduce((s,o)=>s+Number(o.total||0),0),week=paid.filter(o=>now-new Date(o.createdAt).getTime()<7*day).reduce((s,o)=>s+Number(o.total||0),0),month=paid.filter(o=>now-new Date(o.createdAt).getTime()<30*day).reduce((s,o)=>s+Number(o.total||0),0),byProduct={};paid.forEach(o=>(o.items||[]).forEach(i=>{byProduct[i.name]=(byProduct[i.name]||0)+i.qty}));return json(res,200,{revenue,today,week,month,avgOrder:paid.length?revenue/paid.length:0,paidOrders:paid.length,totalOrders:db.orders.length,topProducts:Object.entries(byProduct).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([name,qty])=>({name,qty})),lowStock:db.products.filter(p=>p.active&&Number(p.stock)<=5).map(p=>({id:p.id,name:p.name,stock:p.stock})),audit:(db.audit||[]).slice(0,30)})}
  if(req.method==='GET'&&url.pathname==='/api/admin/orders/search'){const q=String(url.searchParams.get('q')||'').trim().toLowerCase(),db=readDB(),list=!q?db.orders:db.orders.filter(o=>[o.number,o.customer?.name,o.customer?.email,o.customer?.phone,o.customer?.uid].some(v=>String(v||'').toLowerCase().includes(q)));return json(res,200,list.slice(0,100))}
  if(req.method==='POST'&&url.pathname==='/api/admin/products'){
    try{const b=await body(req);if(!b.name||!Number.isFinite(Number(b.price))||!hasImage(b))return json(res,400,{error:'image_required'});const db=readDB(),p={id:b.id||safeId(),sku:String(b.sku||'CK-'+crypto.randomBytes(3).toString('hex').toUpperCase()).slice(0,80),name:String(b.name).slice(0,150),category:b.category||'services',price:Number(b.price),cost:Number(b.cost)||0,oldPrice:b.oldPrice?Number(b.oldPrice):null,tag:b.tag||'رقمي',tags:Array.isArray(b.tags)?b.tags.slice(0,20):[],stock:Math.max(0,Number(b.stock)||0),active:b.active!==false,featured:!!b.featured,sortOrder:Number(b.sortOrder)||0,description:String(b.description||'').slice(0,3000),seoTitle:String(b.seoTitle||'').slice(0,70),seoDescription:String(b.seoDescription||'').slice(0,170),image:b.image,images:Array.isArray(b.images)?b.images.slice(0,8):[],cover:b.cover||'linear-gradient(135deg,#12384a,#19b9d6)'};db.products.push(p);audit(db,'product_created',{id:p.id,name:p.name});writeDB(db);return json(res,201,p)}catch{return json(res,400,{error:'bad_request'})}
  }
  const pm=url.pathname.match(/^\/api\/admin\/products\/([^/]+)$/);if(pm&&req.method==='PATCH'){
    try{const b=await body(req),db=readDB(),p=db.products.find(p=>p.id===pm[1]);if(!p)return json(res,404,{error:'not_found'});if(b.active===true&&!hasImage({...p,...b}))return json(res,400,{error:'image_required'});for(const k of ['name','sku','category','price','cost','oldPrice','tag','tags','stock','active','featured','sortOrder','description','seoTitle','seoDescription','cover','image','images'])if(k in b)p[k]=b[k];p.price=Number(p.price);p.cost=Number(p.cost)||0;p.stock=Math.max(0,Number(p.stock)||0);p.sortOrder=Number(p.sortOrder)||0;audit(db,'product_updated',{id:p.id,name:p.name});writeDB(db);return json(res,200,p)}catch{return json(res,400,{error:'bad_request'})}
  }
  if(pm&&req.method==='DELETE'){const db=readDB(),p=db.products.find(p=>p.id===pm[1]);db.products=db.products.filter(p=>p.id!==pm[1]);audit(db,'product_deleted',{id:pm[1],name:p?.name||''});writeDB(db);return json(res,200,{ok:true})}
  const om=url.pathname.match(/^\/api\/admin\/orders\/([^/]+)$/);if(om&&req.method==='PATCH'){
    try{const b=await body(req),db=readDB(),o=db.orders.find(o=>o.id===om[1]);if(!o)return json(res,404,{error:'not_found'});if(b.status)o.status=b.status;if(b.markPaid===true)markPaid(db,o,{provider:'manual',id:'admin-'+Date.now()});audit(db,'order_updated',{order:o.number,status:o.status});writeDB(db);return json(res,200,o)}catch{return json(res,400,{error:'bad_request'})}
  }
  if(req.method==='POST'&&url.pathname==='/api/admin/codes'){
    try{const b=await body(req);if(!b.productId||!Array.isArray(b.codes))return json(res,400,{error:'invalid_codes'});const db=readDB(),clean=[...new Set(b.codes.map(x=>String(x).trim()).filter(Boolean))];for(const code of clean)db.codes.push({id:safeId(),productId:b.productId,code,createdAt:new Date().toISOString(),usedAt:null,orderId:null});audit(db,'codes_added',{productId:b.productId,count:clean.length});writeDB(db);return json(res,201,{added:clean.length})}catch{return json(res,400,{error:'bad_request'})}
  }
  return json(res,404,{error:'not_found'});
}

const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
const CSP="default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com; script-src 'self' https://www.gstatic.com https://www.google.com https://www.recaptcha.net https://apis.google.com https://cdn.jsdelivr.net; script-src-elem 'self' https://www.gstatic.com https://www.google.com https://www.recaptcha.net https://apis.google.com https://cdn.jsdelivr.net; img-src 'self' data: https:; connect-src 'self' https://*.googleapis.com https://www.googleapis.com https://*.firebaseio.com https://*.firebaseapp.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com https://www.google.com https://www.recaptcha.net https://api.moyasar.com; frame-src https://www.google.com https://www.recaptcha.net https://accounts.google.com https://*.firebaseapp.com https://*.moyasar.com; frame-ancestors 'none'; base-uri 'self'; object-src 'none'; form-action 'self' https://api.moyasar.com";
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(self)');res.setHeader('Content-Security-Policy',CSP);if(process.env.NODE_ENV==='production')res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return api(req,res,url);let rel=url.pathname==='/'?'index.html':url.pathname.slice(1);const pages={admin:'admin.html',login:'login.html',profile:'profile.html',checkout:'checkout.html','payment-result':'payment-result.html',privacy:'privacy.html',terms:'terms.html',refunds:'refunds.html',contact:'contact.html',about:'about.html'};if(pages[rel])rel=pages[rel];if(/^product\/[A-Za-z0-9-]+$/.test(rel))rel='product.html';const file=path.normalize(path.join(PUBLIC,rel));if(!file.startsWith(PUBLIC))return res.end('Forbidden');fs.stat(file,(err,st)=>{if(err||!st.isFile()){const nf=path.join(PUBLIC,'404.html');if(fs.existsSync(nf)){res.writeHead(404,{'content-type':'text/html; charset=utf-8','cache-control':'no-cache'});return fs.createReadStream(nf).pipe(res)}res.writeHead(404);return res.end('Not found')}const ext=path.extname(file),sensitive=rel==='admin.html';res.writeHead(200,{'content-type':mime[ext]||'application/octet-stream','cache-control':ext==='.html'||sensitive?'no-store':'public, max-age=3600'});fs.createReadStream(file).pipe(res)})});
store.init({seedPath:DB_PATH}).then(()=>server.listen(PORT,()=>console.log(`Cloud Key V5: http://localhost:${PORT} (${store.info().backend})`))).catch(e=>{console.error('Cloud Key storage init failed:',e);process.exit(1)});
